### ISSUE TITLE
yass0.7 - merging step crash

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#115]
Merging stage issue in yass0.7:

*yass.process.run@run 14/02/2018 12:42:36 INFO merging all channels*
Traceback (most recent call last):
File "/usr/local/bin/yass", line 11, in <module>
  load_entry_point('yass-algorithm==0.7.dev0', 'console_scripts', 'yass')()
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
  return self.main(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
  rv = self.invoke(ctx)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
  return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
  return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
  return callback(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/command_line.py", line 54, in sort
  output_dir=output_dir, complete=complete)
File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/command_line.py", line 63, in _run_pipeline
  pipeline.run(config, logger_level, clean, output_dir, complete)
File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/pipeline.py", line 74, in run
  output_directory=output_dir)
File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/process/run.py", line 196, in run
  global_maskedData, global_vbParam, suffStat, CONFIG, L, 0)
File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/mfm.py", line 858, in merge_move
  ELBO = ELBO_Class(maskedData, suffStat, vbParam, param)
File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/mfm.py", line 495, in __init__
  self.calc_ELBO_Opti(args)
File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/mfm.py", line 638, in calc_ELBO_Opti
  prior.beta ** Khat * np.exp(-prior.beta) / math.factorial(Khat))
*OverflowError: long int too large to convert to float*

**Comment by calvinytong** [comment]
Just out of curiosity, what kind of stuff are you running to get these errors? (Trying to figure out what should go in the integration tests)

**Comment by edublancas** [comment]
Just to make sure before I close this, this was fixed on #116, right? @nd2506 

For future reference, in your commit message, you can include the issue number so it's closed automatically: `git commit -m 'fixes #115`

**Comment by nd2506** [comment]
oh ok. yes this was fixed in #120

**Comment by catubc** [comment]
This came out of a simulation sort run... I think Nischal is working on fixing it as it was a the merge step.. Not sure if that helps.

**Comment by nd2506** [comment]
Hi cat. Already fixed this yesterday. Just check if you get any errors now.
