### ISSUE TITLE
_neural_network_detection crash - IndexError: boolean index did not match indexed array along dimension 0; dimension is 29968647 but corresponding boolean dimension is 29943722

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#135]
I ran yass on ella's dataset (~75GB int16) and gpu triage took 1h41mins, but then crashed at the following step (I attach the error log):

2018-02-17 00:53:06.803449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-02-17 00:53:07.480949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
yass.batch.batch@multi_channel_apply 17/02/2018 00:53:07 INFO yass.neuralnetwork.apply.run_detect_triage_featurize took 1.0 hours 41.0 minutes 56.27954912185669 seconds
yass.preprocess.run@_neural_network_detection 17/02/2018 00:53:09 INFO Removing clear indexes outside the allowed range to draw a complete waveform...
yass.preprocess.run@_neural_network_detection 17/02/2018 00:53:14 INFO Saved spike index clear in /media/cat/4TB/paninski/ella/2017-04-25-0/tmp/spike_index_clear.npy...
yass.preprocess.run@_neural_network_detection 17/02/2018 00:53:27 INFO Removing collision indexes outside the allowed range to draw a complete waveform...
yass.preprocess.run@_neural_network_detection 17/02/2018 00:53:50 INFO Saved spike index collision in /media/cat/4TB/paninski/ella/2017-04-25-0/tmp/spike_index_collision.npy...
yass.preprocess.run@_neural_network_detection 17/02/2018 00:54:00 INFO Removing scores for indexes outside the allowed range to draw a complete waveform...
Traceback (most recent call last):
  File "/usr/local/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm==0.7.dev0', 'console_scripts', 'yass')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/yass/command_line.py", line 54, in sort
    output_dir=output_dir, complete=complete)
  File "/usr/local/lib/python3.5/dist-packages/yass/command_line.py", line 63, in _run_pipeline
    pipeline.run(config, logger_level, clean, output_dir, complete)
  File "/usr/local/lib/python3.5/dist-packages/yass/pipeline.py", line 81, in run
    spike_index_all) = preprocess.run(output_directory=output_dir)
  File "/usr/local/lib/python3.5/dist-packages/yass/preprocess/run.py", line 170, in run
    output_directory)
  **File "/usr/local/lib/python3.5/dist-packages/yass/preprocess/run.py", line 405, in _neural_network_detection
    scores = scores[idx]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 29968647 but corresponding boolean dimension is 29943722**
[yass_0.7_elladata_crashlog.txt](https://github.com/paninski-lab/yass/files/1733811/yass_0.7_elladata_crashlog.txt)

**Comment by edublancas** [comment]
ideas @jinhyunglee ?

**Comment by jinhyunglee** [comment]
what is yass 0.7?
is it the same as the master branch?
scores = scores[idx] is line 406 in the master branch. 

from what I see in the master branch, I am not sure..

**Comment by jinhyunglee** [comment]
I see why.
https://github.com/paninski-lab/yass/blob/master/src/yass/neuralnetwork/apply.py#L75
here,
whenever I remove spikes from clear, I should remove it from score too
