### ISSUE TITLE
KeyError: 'max_n_spikes' in - "/usr/local/lib/python3.5/dist-packages/yass/config/config.py", line 62

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#138]
02-19 16:07:19.440825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-02-19 16:07:20.189663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-02-19 16:07:20.706119: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-02-19 16:07:21.510137: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-02-19 16:07:22.316015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-02-19 16:07:23.085544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2018-02-19 16:07:23.715807: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
yass.batch.batch@multi_channel_apply 19/02/2018 16:07:24 INFO yass.neuralnetwork.apply.run_detect_triage_featurize took 1.0 hours 50.0 minutes 43.31230592727661 seconds
yass.preprocess.run@_neural_network_detection 19/02/2018 16:07:25 INFO Removing clear indexes outside the allowed range to draw a complete waveform...
yass.preprocess.run@_neural_network_detection 19/02/2018 16:07:29 INFO Saved spike index clear in /media/cat/4TB/paninski/ella/2017-04-25-0/tmp/spike_index_clear.npy...
yass.preprocess.run@_neural_network_detection 19/02/2018 16:07:37 INFO Removing collision indexes outside the allowed range to draw a complete waveform...
yass.preprocess.run@_neural_network_detection 19/02/2018 16:08:11 INFO Saved spike index collision in /media/cat/4TB/paninski/ella/2017-04-25-0/tmp/spike_index_collision.npy...
yass.preprocess.run@_neural_network_detection 19/02/2018 16:08:22 INFO Removing scores for indexes outside the allowed range to draw a complete waveform...
2018-02-19 16:08:35.367036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
yass.preprocess.run@_neural_network_detection 19/02/2018 16:08:35 INFO Saved rotation matrix in /media/cat/4TB/paninski/ella/2017-04-25-0/tmp/rotation.npy...
yass.preprocess.run@_neural_network_detection 19/02/2018 16:10:57 INFO Saved spike scores in /media/cat/4TB/paninski/ella/2017-04-25-0/tmp/score_clear.npy...
yass.process.run@run 19/02/2018 16:12:06 INFO Triaging...
yass.process.run@run 19/02/2018 16:15:00 INFO Randomly subsampling...
Traceback (most recent call last):
  File "/usr/local/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm==0.7.dev0', 'console_scripts', 'yass')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/yass/command_line.py", line 54, in sort
    output_dir=output_dir, complete=complete)
  File "/usr/local/lib/python3.5/dist-packages/yass/command_line.py", line 63, in _run_pipeline
    pipeline.run(config, logger_level, clean, output_dir, complete)
  File "/usr/local/lib/python3.5/dist-packages/yass/pipeline.py", line 86, in run
    output_directory=output_dir)
  File "/usr/local/lib/python3.5/dist-packages/yass/process/run.py", line 84, in run
    CONFIG.clustering.max_n_spikes)
  File "/usr/local/lib/python3.5/dist-packages/yass/config/config.py", line 62, in __getattr__
    return FrozenJSON(self._data[name])
KeyError: 'max_n_spikes'

**Comment by jinhyunglee** [comment]
You need to update your config file to a newer version

**Comment by catubc** [comment]
Ok, I guess we can close this for now as long as it is noted somewhere.
