### ISSUE TITLE
MemoryError: "/usr/local/lib/python3.5/dist-packages/yass/mfm.py", line 1017,

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#141]
Crash during post (during?) channel merging step:

yass.process.cluster@run_cluster_loccation 19/02/2018 16:40:59 INFO Processing channel 504
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:01 INFO Processing channel 505
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:04 INFO Processing channel 506
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:07 INFO Processing channel 507
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:09 INFO Processing channel 508
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:11 INFO Processing channel 509
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:13 INFO Processing channel 510
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:14 INFO Processing channel 511
yass.process.cluster@run_cluster_loccation 19/02/2018 16:41:17 INFO merging all channels
Traceback (most recent call last):
  File "/usr/local/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm==0.7.dev0', 'console_scripts', 'yass')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/yass/command_line.py", line 54, in sort
    output_dir=output_dir, complete=complete)
  File "/usr/local/lib/python3.5/dist-packages/yass/command_line.py", line 63, in _run_pipeline
    pipeline.run(config, logger_level, clean, output_dir, complete)
  File "/usr/local/lib/python3.5/dist-packages/yass/pipeline.py", line 86, in run
    output_directory=output_dir)
  File "/usr/local/lib/python3.5/dist-packages/yass/process/run.py", line 94, in run
    spike_index, CONFIG)
  File "/usr/local/lib/python3.5/dist-packages/yass/process/cluster.py", line 209, in run_cluster_loccation
    idx_triage = cluster_triage(global_vbParam, global_score, 3)
  File "/usr/local/lib/python3.5/dist-packages/yass/mfm.py", line 1017, in cluster_triage
    np.matmul(scoremhat[:, :, :, np.newaxis, :], prec),
MemoryError

**Comment by jinhyunglee** [comment]
this is totally possible. the PR that I put it should fix this issue by bypassing final merge.

**Comment by edublancas** [comment]
Should I close this issue?
