### ISSUE TITLE
key error in retinal_evaulation.py 

### ISSUE THREAD

**Issue by calvinytong** [paninski-lab/yass#149]
Running the retinal evaluation script yields

```
Traceback (most recent call last):
  File "retinal_evaluation.py", line 266, in <module>
    main()
  File "retinal_evaluation.py", line 195, in main
    spike_train = run(config=config)
  File "/home/calvin/yass/src/yass/pipeline.py", line 71, in run
    set_config(config)
  File "/home/calvin/yass/src/yass/__init__.py", line 49, in set_config
    CONFIG = Config(config)
  File "/home/calvin/yass/src/yass/config/config.py", line 97, in __init__
    mapping = self._validate(mapping)
  File "/home/calvin/yass/src/yass/config/config.py", line 157, in _validate
    mapping = validator.validate()
  File "/home/calvin/yass/src/yass/config/validator.py", line 106, in validate
    self._validate_fields()
  File "/home/calvin/yass/src/yass/config/validator.py", line 75, in _validate_fields
    value = self.d[section][subsection]
KeyError: 'dtype'
```

FYI @edublancas @jinhyunglee

**Comment by calvinytong** [comment]
Assuming this has something to do with all of the config changes going on recently

**Comment by calvinytong** [comment]
It is not there. What should it be?

**Comment by jinhyunglee** [comment]
check config files in the examples/ folder

**Comment by calvinytong** [comment]
Okay I got it working thanks
