### ISSUE TITLE
yass won't restart post-filter process

### ISSUE THREAD

**Issue by catubc** [paninski-lab/yass#186]
If a crash occurs post-filtering, I think the path_to_recordings variable is being passed as an object instead of a string.

**Comment by edublancas** [comment]
Can you elaborate on this? Do you have an error traceback?

**Comment by catubc** [comment]
The variable path_to_recordings is supposed to be a string, but if a crash occurs after filter, the path_to_recordings variable sent to the standardization step is an object.

I think that as yass checks the filtering step to see if it's done, it replaces the variable with an object instead of the original string.

**Comment by catubc** [comment]
So here's the error that we get:

at@catlab:~/code/openneuron$ yass sort --logger_level=DEBUG /home/cat/code/yass/data/ej49_data1_set1.yaml 
yass.preprocess.run@run 30/03/2018 16:29:31 INFO Output dtype for transformed data will be float32
yass.preprocess.run@run 30/03/2018 16:29:31 INFO Temporary folder /home/cat/code/yass/data/tmp/ already exists, output will be stored there
yass.preprocess.whiten@matrix 30/03/2018 16:29:31 INFO Computing whitening matrix...
Traceback (most recent call last):
  File "/usr/local/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm==0.7.dev0', 'console_scripts', 'yass')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/command_line.py", line 54, in sort
    output_dir=output_dir, complete=complete)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/command_line.py", line 63, in _run_pipeline
    pipeline.run(config, logger_level, clean, output_dir, complete)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/pipeline.py", line 100, in run
    whiten_filter) = preprocess.run(output_directory=output_dir)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/preprocess/run.py", line 122, in run
    if_file_exists=if_file_exists)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/util.py", line 429, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/preprocess/whiten.py", line 81, in matrix
    max_memory)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/batch/batch.py", line 64, in __init__
    loader=loader)
  File "/usr/local/lib/python2.7/dist-packages/yass_algorithm-0.7.dev0-py2.7.egg/yass/batch/reader.py", line 64, in __init__
    path_to_yaml = path_to_recordings.replace('.bin', '.yaml')
TypeError: replace() takes exactly 2 arguments (3 given)
