### ISSUE TITLE
ERROR loading `import cudaSpline as deconv`. What CUDA version should I use?

### ISSUE THREAD

**Issue by jamesjun** [paninski-lab/yass#292]
I tried CUDA 8.0 and 10.0 but I still get the following error:

(yass) jjun@ccmlin000:10chan$ yass sort config.yaml
Traceback (most recent call last):
  File "/mnt/home/jjun/conda/envs/yass/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm', 'console_scripts', 'yass')()
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/mnt/home/jjun/src/yass/src/yass/command_line.py", line 19, in <module>
    from yass import pipeline
  File "/mnt/home/jjun/src/yass/src/yass/pipeline.py", line 32, in <module>
    from yass import (preprocess, detect, cluster, postprocess,
  File "/mnt/home/jjun/src/yass/src/yass/deconvolve/__init__.py", line 1, in <module>
    from yass.deconvolve.run import run
  File "/mnt/home/jjun/src/yass/src/yass/deconvolve/run.py", line 13, in <module>
    from yass.deconvolve.match_pursuit_gpu import deconvGPU, deconvGPU2
  File "/mnt/home/jjun/src/yass/src/yass/deconvolve/match_pursuit_gpu.py", line 15, in <module>
    import cudaSpline as deconv
ImportError: /mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/deconv-0.0.0-py3.6-linux-x86_64.egg/cudaSpline.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E

**Comment by catubc** [comment]
Yes, that might be a cuda error.  Cuda 10 should work (cuda 8 i don't think we ever tested) but you may need to follow the correct order on compiling/installing pytorch.  That is my recollection with this error.  I would start from scratch again and make sure cuda 10 is linked when compiling pytorch.

If it still doesn't work, please post the history and error log.

**Comment by jamesjun** [comment]
It was resolved after running `module load cuda gcc` before creating a conda environment. Now I have a new error:

(yass) jjun@ccmlin000:10chan$ yass sort config.yaml
Traceback (most recent call last):
  File "/mnt/home/jjun/conda/envs/yass/bin/yass", line 6, in <module>
    from yass.command_line import cli
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 19, in <module>
    from yass import pipeline
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 32, in <module>
    from yass import (preprocess, detect, cluster, postprocess,
  File "/mnt/home/jjun/conda/envs/yass/lib/python3.6/site-packages/yass/deconvolve/__init__.py", line 1, in <module>
    from yass.deconvolve.run import run
ImportError: cannot import name 'run'
