### ISSUE TITLE
denoise: ValueError: cannot reshape array of size 0 into shape (0,newaxis)

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#294]
Hi,
I encounter this error when I launch yass on my data, it seems to be generated by the absence of spike detected on a channel.

I solve this issue by increasing duration to find spikes on all channels.

yass.cluster.run@run 22/10/2019 17:22:09 INFO denoise
  0%|                                                    | 0/50 [00:00<?, ?it/s]/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/numpy/core/_methods.py:154: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/cluster/util.py:549: RuntimeWarning: invalid value encountered in greater
  idx = np.where(energy > 0.5)[0]
  0%|                                                    | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 137, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 243, in initial_block
    full_run=True)    
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/cluster/run.py", line 166, in run
    denoise_wf(fnames_input)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/cluster/util.py", line 567, in denoise_wf
    denoised_wf = denoised_wf.reshape(n_data, -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

**Comment by jinhyunglee** [comment]
hi thank you for reporting bugs.
it seems like you are using no neural net version?
I pushed the fix. let me know if the update code leads to another bug

**Comment by llobetv** [comment]
Hi, thanks !

now i got this:

yass.cluster.run@run 23/10/2019 14:50:15 INFO re-estimate templates of low firing rate units
Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 137, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 243, in initial_block
    full_run=True)    
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/cluster/run.py", line 226, in run
    n_max_spikes=100)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/cluster/util.py", line 877, in denoise_then_estimate_template
    torch.from_numpy(wfs_reshaped).float().cuda())[0].data.cpu().numpy().reshape(
TypeError: 'NoneType' object is not callable

**Comment by llobetv** [comment]
The error disappear if I relaunch yass a 2nd times after the error
