### ISSUE TITLE
KeyError: "Trying to access a key that does not exist, (min_split_spikes) keys are: dict_keys(['threshold', 'deconv_gpu', 'update_templates', 'template_update_time', 'drift_model', 'neuron_discover_time'])"

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#295]
Hi,
I got this error (that I also encounter when I launch yass on exemple data provide with yass):

It seems that in config.yaml provide in samples/10chan their is some arguments that are missing 

yass.postprocess.run@post_process 22/10/2019 17:43:45 INFO 122 units after removing duplicate unitsthat you provide
 inpput to block2:  tmp/block_1/cluster_post_process/templates.npy
yass.pipeline@iterative_block 22/10/2019 17:43:45 INFO DECONV
Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/config/config.py", line 56, in __getattr__
    return FrozenJSON(self._data[name])
KeyError: 'min_split_spikes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 152, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 284, in iterative_block
    run_chunk_sec=run_chunk_sec)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 77, in run
    CONFIG = make_CONFIG2(CONFIG)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/util.py", line 49, in make_CONFIG2
    CONFIG2.deconvolution.min_split_spikes = CONFIG.deconvolution.min_split_spikes
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/config/config.py", line 60, in __getattr__
    name, self._data.keys()))
KeyError: "Trying to access a key that does not exist, (min_split_spikes) keys are: dict_keys(['threshold', 'deconv_gpu', 'update_templates', 'template_update_time', 'drift_model', 'neuron_discover_time'])"

Best,
Victor

**Comment by catubc** [comment]
Hi Victor.  Yass had an update last week or so with new parameters in the config.yaml file. Please see new updated config.yaml file here:  https://github.com/paninski-lab/yass/blob/master/examples/config_sample.yaml

In the future we will try to have a better way to update CONFIG file.  

Thanks,
