### ISSUE TITLE
deconvolve: IndexError: index 12 is out of bounds for axis 0 with size 12

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#297]
I encounter this error when i try to launch yass on exemple data:

self.idx_list[batch_id] call index 12 when dimension is (12, 2). 

batch_id is supposed to go until 24.

I got the same issue when I launch yass on other data: batch_id go up to 192 when self.idx_list is (188, 2)

Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 152, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 284, in iterative_block
    run_chunk_sec=run_chunk_sec)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 148, in run
    run_chunk_sec)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 275, in deconv_ONgpu2
    output_directory)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 580, in run_deconv_with_templates_update
    d_gpu.run(chunk_id)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/match_pursuit_gpu.py", line 233, in run
    self.load_data(chunk_id)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/match_pursuit_gpu.py", line 543, in load_data
    chunk_id, add_buffer=True).T
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/reader.py", line 73, in read_data_batch
    data_start, data_end = self.idx_list[batch_id]
IndexError: index 12 is out of bounds for axis 0 with size 12

**Comment by llobetv** [comment]
I don't know wht you've done but bug is fixed, 

thanks

**Comment by catubc** [comment]
Yes, this bug was fixed.
