### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/block_2/deconv/segs/000005.npz'

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#300]
Hi guys,

a bug that appear, probably because you are working on yass, in case it can help you:

yass.pipeline@run 24/10/2019 13:48:46 INFO YASS version: 0.10dev
yass.preprocess.run@run 24/10/2019 13:48:46 INFO # of chunks: 291
yass.preprocess.run@run 24/10/2019 13:48:46 INFO Temporary folder tmp/preprocess already exists, output will be stored there
yass.preprocess.run@run 24/10/2019 13:48:46 INFO Output dtype for transformed data will be float32
yass.pipeline@initial_block 24/10/2019 13:48:46 INFO INITIAL DETECTION
yass.pipeline@initial_block 24/10/2019 13:48:46 INFO INITIAL CLUSTERING
yass.postprocess.run@run 24/10/2019 13:48:46 INFO 640 units are in
yass.postprocess.run@post_process 24/10/2019 13:48:46 INFO 481 units after removing off centered units
484it [00:04, 97.30it/s]                                                        
yass.postprocess.run@post_process 24/10/2019 13:48:53 INFO 290 units after removing high mad units
yass.postprocess.run@post_process 24/10/2019 13:48:56 INFO 161 units after removing duplicate units
 inpput to block2:  tmp/block_1/cluster_post_process/templates.npy
yass.pipeline@iterative_block 24/10/2019 13:48:56 INFO DECONV
Processing templates:  tmp/block_1/cluster_post_process/templates.npy
 ICD TUREND ON .....
   templates being updated every  120  sec
    d_gpu.neuron_discover_time:  360
   making SVD data... (todo: move to GPU)
  making temp_temp filters (todo: move to GPU)
  making template bsplines
  ... moving coefficients to cuda objects
Forward deconv only  5  sec,  0 / 569
Process Process-81:
Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 420, in run_deconv_no_templates_update_parallel
    d_gpu.run(chunk_id)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/match_pursuit_gpu.py", line 238, in run
    self.subtraction_step()
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/match_pursuit_gpu.py", line 727, in subtraction_step
    total_time = self.subtract_cpp()
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/match_pursuit_gpu.py", line 908, in subtract_cpp
    self.tempScaling_array
TypeError: subtract_splines(): incompatible function arguments. The following argument types are supported:
    1. (energy: at::Tensor, times_indices: at::Tensor, times_offsets: at::Tensor, template_ids: at::Tensor, templates: cudaSpline.BatchedTemplates, tempScaling: float) -> None

Invoked with: tensor([[-660.4733, -657.8095, -660.5699,  ..., -664.1783, -663.6525,
         -663.7109],
        [-446.4852, -444.0013, -438.9771,  ..., -452.1943, -455.0314,
         -456.2298],
        [-432.5251, -428.8642, -429.3763,  ..., -444.7387, -441.0646,
         -435.6616],
        ...,
        [-126.9543, -127.0029, -126.8833,  ..., -125.5929, -126.0049,
         -126.6169],
        [ -96.8203,  -97.0932,  -97.1969,  ...,  -93.7230,  -94.6949,
          -95.7045],
        [-153.0032, -153.3616, -153.5906,  ..., -150.6422, -151.5247,
         -151.9790]], device='cuda:0'), tensor([     7,     99,    140,  ..., 101806, 101869, 101900], device='cuda:0'), tensor([-0.1187, -0.3686, -0.3120,  ...,  0.1726, -0.1596,  0.3198],
       device='cuda:0'), tensor([ 67,  19, 132,  ..., 138,  96,  78], device='cuda:0'), <cudaSpline.BatchedTemplates object at 0x7f18e0156260>, tensor([2., 2., 2.,  ..., 2., 2., 2.], device='cuda:0')
-------------------------------------------
Total Deconv Speed  205.19  x Realtime
  gathering spike trains and shifts from deconv (todo: parallelize)
  0%|                                                   | 0/569 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 71, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 152, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/pipeline.py", line 284, in iterative_block
    run_chunk_sec=run_chunk_sec)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 148, in run
    run_chunk_sec)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/deconvolve/run.py", line 315, in deconv_ONgpu2
    data = np.load(fname, allow_pickle=True)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/block_2/deconv/segs/000005.npz'

**Comment by catubc** [comment]
Thanks for the report.  YASS is undergoing some final changes next few days.

This bug is due to CUDA code havnig changed.  You will need to re-compile the CUDA code (see landing page instructions).  

Thanks for your patience.

**Comment by llobetv** [comment]
No problem I'm waiting since august so I can wait a bit more.
Thank you for your work!
