### ISSUE TITLE
yass convert: IndexError: index 41 is out of bounds for axis 0 with size 10

### ISSUE THREAD

**Issue by llobetv** [paninski-lab/yass#303]
Hi,

In generate.py l 65 you must change :

templates_mainc = np.argmax(np.max(templates, axis=1), axis=0)

to 

templates_mainc = np.argmax(np.max(templates, axis=1), axis=1)
(or even templates_mainc = np.argmax(np.max(np.abs(templates), axis=1), axis=1))

Traceback (most recent call last):
  File "/users/nsr/llobet/anaconda3/envs/yass/bin/yass", line 10, in <module>
    sys.exit(cli())
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/command_line.py", line 176, in export
    templates)
  File "/users/nsr/llobet/anaconda3/envs/yass/lib/python3.6/site-packages/yass/export/generate.py", line 71, in pc_feature_ind
    spikes_mainc[j] = templates_mainc[spike_train[j, 1]]
IndexError: index 41 is out of bounds for axis 0 with size 10

**Comment by catubc** [comment]
Hi.  Thanks for the bug report.  We've not used these functions for a while. Will fix it soon.
