### ISSUE TITLE
crash during final deconv

### ISSUE THREAD

**Issue by wueric** [paninski-lab/yass#318]
Stack trace, running latest on master:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/yass/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm', 'console_scripts', 'yass')()
  File "/home/ubuntu/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/envs/yass/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/yass/src/yass/command_line.py", line 85, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/home/ubuntu/yass/src/yass/pipeline.py", line 185, in run
    CONFIG)
  File "/home/ubuntu/yass/src/yass/pipeline.py", line 607, in final_deconv
    remove_meta_data=True)
  File "/home/ubuntu/yass/src/yass/pipeline.py", line 726, in final_deconv_with_template_updates_v2
    first_batch)
  File "/home/ubuntu/yass/src/yass/pipeline.py", line 1201, in deconv_pass1
    run_chunk_sec=run_chunk_sec)
  File "/home/ubuntu/yass/src/yass/deconvolve/run.py", line 111, in run
    run_chunk_sec)
  File "/home/ubuntu/yass/src/yass/deconvolve/run.py", line 174, in deconv_ONgpu
    d_gpu = run_core_deconv(d_gpu, CONFIG)
  File "/home/ubuntu/yass/src/yass/deconvolve/run.py", line 268, in run_core_deconv
    d_gpu.initialize(move_data_to_gpu=False)
  File "/home/ubuntu/yass/src/yass/deconvolve/match_pursuit_gpu_new.py", line 155, in initialize
    self.initialize_shift_svd()
  File "/home/ubuntu/yass/src/yass/deconvolve/match_pursuit_gpu_new.py", line 232, in initialize_shift_svd
    pad_len=self.pad_len, jitter_len=self.jitter_len, sparse=True)
  File "/home/ubuntu/yass/src/yass/deconvolve/utils.py", line 524, in __init__
    neigh_chans, min_loc_ref=min_loc_orig+pad_len)
  File "/home/ubuntu/yass/src/yass/deconvolve/utils.py", line 811, in align_templates
    index_start = val.argmin()
ValueError: attempt to get argmin of an empty sequence

**Comment by catubc** [comment]
Thanks for the bug report, we're looking at it shortly.

**Comment by jinhyunglee** [comment]
hi @wueric, 

I pushed the fix. can you retry and let me know?

but this should not really happen. Can you share your config file to make sure it is run correctly?

**Comment by jinhyunglee** [comment]
@wueric, any update?

**Comment by wueric** [comment]
i'll update you tomorrow.

**Comment by wueric** [comment]
appears to have been solved.

In the previous version when it was crashing, the issue seemed to be with the particular dataset and not with the config. I've used the same config for everything, but that particular dataset had issues.
