### ISSUE TITLE
Crash during ptp_split

### ISSUE THREAD

**Issue by Dradeliomecus** [paninski-lab/yass#320]
When running yass, the sample test worked, but it didn't with my data.
I run yass without a neural network for spike detections.
Here is the error:

yass.pipeline@run 30/03/2020 11:55:06 INFO YASS version: 2.0
yass.preprocess.run@run 30/03/2020 11:55:06 INFO # of chunks: 184
yass.preprocess.run@run 30/03/2020 11:55:06 INFO Temporary folder tmp/preprocess already exists, output will be stored there
yass.preprocess.run@run 30/03/2020 11:55:06 INFO Output dtype for transformed data will be float32
yass.pipeline@initial_block 30/03/2020 11:55:06 INFO INITIAL DETECTION
yass.pipeline@initial_block 30/03/2020 11:55:06 INFO INITIAL CLUSTERING
 inpput to block2:  tmp/block_1/cluster_post_process/templates.npy
yass.pipeline@iterative_block 30/03/2020 11:55:06 INFO DECONV
yass.pipeline@iterative_block 30/03/2020 11:55:06 INFO RESIDUAL COMPUTATION
yass.pipeline@iterative_block 30/03/2020 11:55:06 INFO RECLUSTERING
yass.cluster.run@run 30/03/2020 11:55:06 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 30/03/2020 11:55:06 INFO Get Spike PTP
100%|███████████████████████████████████████████| 60/60 [00:02<00:00, 24.47it/s]
Traceback (most recent call last):
  File "/users/nsr/wyngaard/miniconda3/envs/yass2/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm', 'console_scripts', 'yass')()
  File "/users/nsr/wyngaard/miniconda3/envs/yass2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/wyngaard/miniconda3/envs/yass2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/nsr/wyngaard/miniconda3/envs/yass2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/wyngaard/miniconda3/envs/yass2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/wyngaard/miniconda3/envs/yass2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/export/home1/users/nsr/wyngaard/yass/src/yass/command_line.py", line 80, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/export/home1/users/nsr/wyngaard/yass/src/yass/pipeline.py", line 162, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/export/home1/users/nsr/wyngaard/yass/src/yass/pipeline.py", line 362, in iterative_block
    full_run=True)
  File "/export/home1/users/nsr/wyngaard/yass/src/yass/cluster/run.py", line 156, in run
    denoiser)
  File "/export/home1/users/nsr/wyngaard/yass/src/yass/cluster/ptp_split.py", line 59, in run_split_on_ptp
    ptp_raw, ptp_deno = getcleanptp.compute_ptps()
  File "/export/home1/users/nsr/wyngaard/yass/src/yass/cluster/getptp.py", line 255, in compute_ptps
    del dat, idx_in, spike_index_batch, t_index, c_index, residuals, wfs, denoised_wfs
UnboundLocalError: local variable 'denoised_wfs' referenced before assignment

I tried debugging this on my own, and tried to get rid of the del denoised_wfs.
When I did that, I got the same error, but with the variable 'ptps_denoised'.
I found out that all self.denoiser are None, could this be what's causing the issue?

Thank you

**Comment by jinhyunglee** [comment]
hi have you pulled the latest code?

**Comment by Dradeliomecus** [comment]
Hi,

Yes, I use Yass 2.0 (installed friday March 27th) with cuda 10.2 on Ubuntu 18.04.

**Comment by jinhyunglee** [comment]
can you check if it fixed the problem?

have you tried to use nn models?
I can direct you with training neural nets (it is very simple!)

**Comment by Dradeliomecus** [comment]
Thank you very much!
It works fine now!

I want to compare when using the nn model vs not using it.
I already know how to train it, but thank you!
