### ISSUE TITLE
installation fails on fresh ubuntu 20.04

### ISSUE THREAD

**Issue by grg2rsr** [paninski-lab/yass#331]
Hi,
I got stuck trying to install yass:

- I am on a fresh ubuntu LTS 20.04, GPU is a GTX 1070 with nvidia driver verision 440.10
- I installed the cuda toolkit 11 form the [.deb package](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=deblocal)
- pytorch version 1.4.0
- gcc 9.3.0 which is according to the [compatibility table](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz3x7mwvZrG) from nvidia the matching one to toolkit 11

From the [wiki install instructions](https://github.com/paninski-lab/yass/wiki/Installation-Local) all steps run smoothly until step 7, where I get 

```
THCudaCheck FAIL file=/tmp/pip-req-build-8yht7tdu/aten/src/THC/THCGeneral.cpp line=50 error=804 : forward compatibility was attempted on non supported HW
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    setup(name='deconv',
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 174, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 160, in call_command
    self.run_command(cmdname)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 372, in build_extensions
    build_ext.build_extensions(self)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 288, in unix_wrap_compile
    "'-fPIC'"] + cflags + _get_cuda_arch_flags(cflags)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1013, in _get_cuda_arch_flags
    capability = torch.cuda.get_device_capability()
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/torch/cuda/__init__.py", line 320, in get_device_capability
    prop = get_device_properties(device)
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/torch/cuda/__init__.py", line 325, in get_device_properties
    _lazy_init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/georg/anaconda3/envs/yass/lib/python3.8/site-packages/torch/cuda/__init__.py", line 197, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (804) : forward compatibility was attempted on non supported HW at /tmp/pip-req-build-8yht7tdu/aten/src/THC/THCGeneral.cpp:50
```

thanks for help

**Comment by catubc** [comment]
Thanks for the report.  We are currently recommending that pytorch==1.2 be installed via anaconda.  Some of the latest packages required by YASS appear to be conflicting at times with pytorch.  We added a note in the installation wiki now.

Please try following the instructions again (using conda install pytorch==1.2) and post the report here.

**Comment by grg2rsr** [comment]
thank you for you reply. Installation succeded, but running yass on the sample file crashes

```
(yass) georg@georg-desktop:~/code/yass/samples/10chan$ yass sort config.yaml 
yass.pipeline@run 21/07/2020 11:22:13 INFO YASS version: 2.0
yass.preprocess.run@run 21/07/2020 11:22:13 INFO # of chunks: 6
yass.preprocess.run@run 21/07/2020 11:22:13 INFO Temporary folder tmp/preprocess already exists, output will be stored there
yass.preprocess.run@run 21/07/2020 11:22:13 INFO Output dtype for transformed data will be float32
yass.pipeline@initial_block 21/07/2020 11:22:13 INFO INITIAL DETECTION
THCudaCheck FAIL file=/tmp/pip-req-build-58y_cjjl/aten/src/THC/THCGeneral.cpp line=50 error=30 : unknown error
Traceback (most recent call last):
  File "/home/georg/anaconda3/envs/yass/bin/yass", line 33, in <module>
    sys.exit(load_entry_point('yass-algorithm', 'console_scripts', 'yass')())
  File "/home/georg/anaconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/georg/anaconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/georg/anaconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/georg/anaconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/georg/anaconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/georg/code/yass/src/yass/command_line.py", line 80, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/home/georg/code/yass/src/yass/pipeline.py", line 150, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/home/georg/code/yass/src/yass/pipeline.py", line 286, in initial_block
    run_chunk_sec=run_chunk_sec)
  File "/home/georg/code/yass/src/yass/detect/run.py", line 107, in run
    run_chunk_sec=run_chunk_sec)
  File "/home/georg/code/yass/src/yass/detect/run.py", line 135, in run_neural_network
    CONFIG.channel_index, CONFIG)
  File "/home/georg/code/yass/src/yass/neuralnetwork/model_detector.py", line 15, in __init__
    torch.cuda.set_device(CONFIG.resources.gpu_id)
  File "/home/georg/anaconda3/envs/yass/lib/python3.7/site-packages/torch/cuda/__init__.py", line 281, in set_device
    torch._C._cuda_setDevice(device)
  File "/home/georg/anaconda3/envs/yass/lib/python3.7/site-packages/torch/cuda/__init__.py", line 179, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /tmp/pip-req-build-58y_cjjl/aten/src/THC/THCGeneral.cpp:50
```

**Comment by catubc** [comment]
Thanks for the report.  It seems the cuda code was not properly installed.

We recommend starting with a completely new install from scratch (i.e. from step 1 in the installation script and a new virtual env) and then letting us know if you still get an error.

**Comment by catubc** [comment]
Assume this issue was resolved.
