### ISSUE TITLE
Size mismatch for out.weight in loading state_dict for Detect

### ISSUE THREAD

**Issue by Dradeliomecus** [paninski-lab/yass#332]
I have an issue which resembles #321.

I ran a fresh yass on my dataset, and got the following error:
```
$ yass sort config.yaml 
Matplotlib is building the font cache; this may take a moment.
yass.pipeline@run 25/08/2020 09:59:09 INFO YASS version: 2.0
yass.preprocess.run@run 25/08/2020 09:59:09 INFO # of chunks: 198
yass.preprocess.run@run 25/08/2020 09:59:09 INFO Creating temporary folder: 1/tmp/preprocess
yass.preprocess.run@run 25/08/2020 09:59:09 INFO Output dtype for transformed data will be int16
100%|███████████████████████████████████████████████████████████████████████████████████████████| 198/198 [01:19<00:00,  2.48it/s]
yass.preprocess.util@merge_filtered_files 25/08/2020 10:00:30 INFO ...saving standardized file: 1/tmp/preprocess/standardized.bin
yass.preprocess.run@run 25/08/2020 10:00:44 INFO Saving params...
yass.pipeline@initial_block 25/08/2020 10:00:44 INFO INITIAL DETECTION
Traceback (most recent call last):
  File "/users/nsr/wyngaard/miniconda3/envs/yass/bin/yass", line 33, in <module>
    sys.exit(load_entry_point('yass-algorithm', 'console_scripts', 'yass')())
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/command_line.py", line 80, in sort
    calculate_rf=calculate_rf, visualize=visualize)#,
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/pipeline.py", line 150, in run
    run_chunk_sec = CONFIG.clustering_chunk)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/pipeline.py", line 286, in initial_block
    run_chunk_sec=run_chunk_sec)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/detect/run.py", line 106, in run
    run_chunk_sec=run_chunk_sec)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/detect/run.py", line 136, in run_neural_network
    detector.load(CONFIG.neuralnetwork.detect.filename)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/neuralnetwork/model_detector.py", line 145, in load
    self.load_state_dict(checkpoint)
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Detect:
	size mismatch for out.weight: copying a param with shape torch.Size([1, 56]) from checkpoint, the shape in current model is torch.Size([1, 88]).
```

Here is my `config.yaml`:
```
########################################################
# YASS configuration example (all sections and values) #
########################################################

data:
  # project's root folder, data will be loaded and saved here
  # can be an absolute or relative path
  root_folder: ./1/
  # recordings filename (must be a binary file), details about the recordings
  # are specified in the recordings section
  recordings: data.dat
  # channel geometry filename , supports txt (one x, y pair per line,
  # separated by spaces) or a npy file with shape (n_channels, 2),
  # where every row contains a x, y pair. see yass.geometry.parse for details
  geometry: geom.txt
  # if you have an initial templates, then yass will skip clustering stage and
  # run the final deconvolution step.
  # make sure that it is a .npy file 
  # with shape (# neurons x # temporal length x # channels)
  # temporal length should be the same as recordings.spike_size_ms*recordings.sampling_rate: 20000
  # channels equals to recordings.n_channels
  # Also make sure the scale (or the unit) of the voltage trace is 
  # the same as yass-preprocessed voltage units. (recommend using yass output templates)
  initial_templates:

resources:
  # CPU multi-processing flag: 1 = use multiple cores
  multi_processing: 1
  # Number of cores to use
  n_processors: 30
  # number of GPUs to use
  n_gpu_processors: 1
  # Length of processing chunk in seconds for multi-processing stages
  n_sec_chunk: 10
  # n_sec_chunk for gpu detection (lower if you get memory error during detection)
  n_sec_chunk_gpu_detect: 0.5
  # n_sec_chunk for gpu deconvolution (lower if you get memory error during deconv)
  n_sec_chunk_gpu_deconv: 5
  # which gpu to use, default is 0, i.e. first gpu;
  gpu_id: 0
  # generate phy visualization files; 0 - do not run; 1: generate phy files
  generate_phy: 1

recordings:
  # precision of the recording – must be a valid numpy dtype
  dtype: int16
  # recording rate (in Hz)
  sampling_rate: 30000
  # number of channels
  n_channels: 64
  # channels spatial radius to consider them neighbors, see
  # yass.geometry.find_channel_neighbors for details
  spatial_radius: 70
  # temporal length of templates in ms. It must capture
  # the full shape of waveforms on all channels 
  # (reminder: there is a propagation delay in waveform shape across channels)
  # but longer means slower
  spike_size_ms: 5
  # temporal length of waveforms in ms (not considering propagation).
  center_spike_size_ms: 2
  # chunks to run clustering on (in seconds)
  # leave blank to run it on full
  clustering_chunk: [0, 300]
  # chunks to run final deconv on (in seconds)
  # leave blank to run it on full
  final_deconv_chunk: #[0, 120]

neuralnetwork:
  # decide to use nn or not
  apply_nn: True
  detect:
    # model name, it can be an absolute path to a model 
    # (e.g. /path/to/my/model.ckpt) or a name of one of models included in yass 
    # (e.g. detect.pt). Check /src/yass/assets/nn_models for the list of available
    # models.
    filename: detect.pt
    # number of filters. you can leave it as it is.
    n_filters: [16, 8, 8] 
  denoise:
    # model name, same rule as detect filename
    filename: denoise.pt
    # number of filters and size. you can leave it as it is.
    n_filters: [16, 8, 4]
    filter_sizes : [5, 11, 21]
  training:
    # input spike train file name. It must be a numpy file of an arroay of n x 2.
    # n is the number of spikes, the first column is the spike times 
    # (center of spikes), the second column is the unit id.
    # if you don't have an input spike train, leave it empty.
    # it will run some parts of yass to make one
    input_spike_train_filname:
    # temporal length of spike to go into nn (default 3ms if left empty)
    # for sorting (not training), you can leave it empty since it will be automatically
    # determined from the above nn files.
    spike_size_ms:

preprocess:
  # apply butterworth filter in the preprocessing step
  apply_filter: True
  # output dtype for transformed data
  dtype: int16
  # filter configuration
  filter:
    # Order of Butterworth filter
    order: 3
    # Low pass frequency (Hz)
    low_pass_freq: 300
    # High pass factor (proportion of sampling rate)
    high_factor: 0.1

detect:
  # threshold 
  # if it is nn detector, must be between [0, 1]
  # if amplitude threshold detector, recommend between [4, 6]
  threshold: 0.5

# All values are optional
cluster:
  # maximum number of spikes per clustering group
  # if the total number of spikes per clustering group exceeds it,
  # it randomly subsample
  max_n_spikes: 10000
  # knn_triage percentage (0.05 means triage 5%)
  knn_triage: 0.05
  # minimum firing rate
  min_fr: 0.2
  # cluster prior information
  prior:
    beta: 1
    a: 1
    lambda0: 0.01
    nu: 5
    V: 2

clean_up:
  # absolute maximum difference between two templates
  # to be considered as distinct
  abs_max_diff: 1.5 # range: 1.0 (oversplits) to 2.0 (overmerges)
  # relative maximum difference (to ptp of larger template)
  rel_max_diff: 0.1 # range: 0.05 (oversplits) to 0.2 (overmerges)
  # minimum ptp allowed (in standardized unit)
  min_ptp: 2.5 # range: 1 (keep more small units) to 8
  # minimum firing rates (in Hz)
  min_fr: 0.2
  # if a template is off centered, it is a gabarage template
  off_center: 5
  mad:
    # minimum gap between theoretical and estimated variance allowed
    min_var_gap: 2
    # how many points of violation are allowed
    max_violations: 10

deconvolution:
    threshold: 50

    # only GPU option available for now
    deconv_gpu: True

    # update templates periodically based on drift model
    update_templates: True

    # discoer new neurons periodically (period as in template update time)
    neuron_discover: True

    # time batches to update templates (sec)
    template_update_time: 300
```

**Comment by catubc** [comment]
Hi.  Thanks for your issue report. 

It is related to incompatible neural-network training vs. testing parameters. 

See here: 
```

RuntimeError: Error(s) in loading state_dict for Detect:
	size mismatch for out.weight: copying a param with shape torch.Size([1, 56]) from checkpoint, the shape in current model is torch.Size([1, 88]).
```

To fix this we generally recommend that yass is run in training mode first to generate novel NNs that fit your config.yaml parameters. 

Please see the wiki here and let us know if you have further questions:

https://github.com/paninski-lab/yass/wiki/Neural-Networks---Loading-and-Retraining

**Comment by Dradeliomecus** [comment]
Ah yes, I forgot to train the neural network!
You should probably make a check and print a message for the users.

I ran `yass train config.yaml`, and I got this error:
```
$ yass train config.yaml 
yass.pipeline_nn_training@run 26/08/2020 11:34:20 INFO YASS version: 2.0
yass.preprocess.run@run 26/08/2020 11:34:20 INFO # of chunks: 198
yass.preprocess.run@run 26/08/2020 11:34:20 INFO Creating temporary folder: 1/tmp/preprocess
yass.preprocess.run@run 26/08/2020 11:34:20 INFO Output dtype for transformed data will be int16
100%|███████████████████████████████████████████████████████████████████████████████████████████| 198/198 [00:49<00:00,  3.98it/s]
yass.preprocess.util@merge_filtered_files 26/08/2020 11:35:11 INFO ...saving standardized file: 1/tmp/preprocess/standardized.bin
yass.preprocess.run@run 26/08/2020 11:35:32 INFO Saving params...
yass.pipeline_nn_training@run 26/08/2020 11:35:32 INFO DETECTION
   batch length to (sec):  10  (longer increase speed a bit)
   length of each seg (sec):  0.5
  0%|                                                                                                      | 0/60 [00:00<?, ?it/s]/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
 13%|████████████▌                                                                                 | 8/60 [00:12<01:18,  1.50s/it]/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
 42%|██████████████████████████████████████▊                                                      | 25/60 [00:14<00:37,  1.09s/it]/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:24<00:00,  2.42it/s]
yass.detect.output@gather_result 26/08/2020 11:35:57 INFO gather detected spikes
yass.detect.output@gather_result 26/08/2020 11:35:57 INFO Total 545233 spikes detected
yass.detect.output@gather_result 26/08/2020 11:35:57 INFO Total 381782 spikes survived after deduplication
yass.pipeline_nn_training@run 26/08/2020 11:35:57 INFO CLUSTERING
yass.cluster.run@run 26/08/2020 11:35:57 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 26/08/2020 11:35:57 INFO Get Spike PTP
  0%|                                                                                                      | 0/60 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/users/nsr/wyngaard/miniconda3/envs/yass/bin/yass", line 33, in <module>
    sys.exit(load_entry_point('yass-algorithm', 'console_scripts', 'yass')())
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/wyngaard/miniconda3/envs/yass/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/command_line.py", line 129, in train
    output_dir=output_dir)#,
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/pipeline_nn_training.py", line 170, in run
    full_run=True)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/cluster/run.py", line 156, in run
    denoiser)
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/cluster/ptp_split.py", line 50, in run_split_on_ptp
    ptp_raw, ptp_deno = getptp.compute_ptps()
  File "/export/home1/users/nsr/wyngaard/dev/yass/src/yass/cluster/getptp.py", line 65, in compute_ptps
    dat = torch.cat((dat, torch.zeros((dat.shape[0], 1)).cuda()), 1)
RuntimeError: Expected object of scalar type Short but got scalar type Float for sequence element 1 in sequence argument at position #1 'tensors'

```

**Comment by catubc** [comment]
Thanks for reporting this issue.  It might be related to a zero-spike bug that sometimes occurs, we've fixed a few of them, but there might be a few left. We'll try to fix this one as well soon.

However, this spike deduplication step seems to indicate that <50% of the spikes were removed during deduplication and this is very low (usually ~90% of the spikes are removed).  

yass.detect.output@gather_result 26/08/2020 11:35:57 INFO gather detected spikes
yass.detect.output@gather_result 26/08/2020 11:35:57 INFO Total 545233 spikes detected
yass.detect.output@gather_result 26/08/2020 11:35:57 INFO Total 381782 spikes survived after deduplication

It might be that your data is not formatted correctly (e.g. C- rather than Fortran order; or data type is not int16).

**Comment by Dradeliomecus** [comment]
Yass was working when we tested it with out dataset in May.
So unless something has changed, our data should still be formatted correctly, but thank you for the heads up!

**Comment by jinhyunglee** [comment]
Hi @Dradeliomecus ,
I don't see any big issue with the line of codes.
The possibility is that somehow `dat.shape[0]` is float instead of int?
can you tell me your pytorch version? I will check if I can replicate the error.

**Comment by Dradeliomecus** [comment]
Hi,
Sorry for not answering sooner.

How can I check `dat.shape[0]`?
I'm using `pytorch1.2.0-cuda100py37h938c94c_0`

**Comment by Dradeliomecus** [comment]
I managed to fix the scalar type issue.
In my `config.yaml` file line 101, in preprocess, I switched from `int16` to `float32` and it now works.
