### ISSUE TITLE
Install yass on ubuntu 20.4

### ISSUE THREAD

**Issue by samuelgarcia** [paninski-lab/yass#341]
I fight hard to install yass on ubuntu 20.4 with python3.8

I don't want to install python 3.7 for the moment. (I already try py3.7 with deadsnake ppa but get other problems)

Maybe some already manage to make it.
Ubuntu 20.4 is more or less the "average standard" for dev  since one year now.

On ubuntu 20.4
nvidia-cuda-toolkit is 10.1 
this should be ok

On ubuntu 20.04 python is 3.8.
With python 3.8 you can not  install torch==1.2
So the older torch is 1.4.
With torch 1.4 I have `have bug "ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory`

I also tried troch 1.5
With torch 1.5 Ihave `ImportError: /home/samuel.garcia/.virtualenvs/py38/lib/python3.8/site-packages/deconv-0.0.0-py3.8-linux-x86_64.egg/cudaSpline.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at12index_selectERKNS_6TensorElS2_`

Any idea to solve this ?

Is there any expert on torch/cuda/compilation ?

In the way yass is design, the user is roce to install 2 submodules for yass: gpu_bspline_interp and gpu_rowshift.

I think you should include then in the main setup to simplify installation fir users.

**Comment by samuelgarcia** [comment]
Here an error I have with
**ubuntu=20.04 / python= 3.7 torch==1.2 / cuda-toolkit=10.1**

```Traceback (most recent call last):
  File "/home/samuel.garcia/.virtualenvs/py37/bin/yass", line 8, in <module>
    sys.exit(cli())
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/yass/command_line.py", line 129, in train
    output_dir=output_dir)#,
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/yass/pipeline_nn_training.py", line 170, in run
    full_run=True)
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/yass/cluster/run.py", line 156, in run
    denoiser)
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/yass/cluster/ptp_split.py", line 50, in run_split_on_ptp
    ptp_raw, ptp_deno = getptp.compute_ptps()
  File "/home/samuel.garcia/.virtualenvs/py37/lib/python3.7/site-packages/yass/cluster/getptp.py", line 47, in compute_ptps
    dat = torch.from_numpy(dat).cuda()
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by catubc** [comment]
Hello Samuel
Yass has not been updated to work with pytorch >1.2 and only works with python 3.7 and torch 1.2 as per the wiki/install instructions. This should be simple to do with any version of Ubuntu as long as you use anaconda as per our install guide. 
Let us know if you have any other questions.

**Comment by oliche** [comment]
Hi @samuelgarcia ! Did you have any luck ?

I tried many configurations, those give the following error message
Ubuntu 20.04 - Cuda toolkit 10.0 - Python3.7 - Pytorch 1.2 - gcc6
Ubuntu 20.04 - Cuda toolkit 10.0 - Python3.7 - Pytorch 1.2 - gcc7
Ubuntu 20.04 - Cuda toolkit 10.0 - Python3.7 - Pytorch 1.2 - gcc5.5
Ubuntu 20.04 - Cuda toolkit  9.0 - Python3.7 - Pytorch 1.2 - gcc5.5


	(yass) olivier@ferret:~/Documents/PYTHON/yass/samples/10chan$ yass sort config.yaml
	Traceback (most recent call last):
	  File "/home/olivier/anaconda3/envs/yass/bin/yass", line 5, in <module>
	    from yass.command_line import cli
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/yass/command_line.py", line 28, in <module>
	    from yass import pipeline
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/yass/pipeline.py", line 31, in <module>
	    from yass import (preprocess, detect, cluster, postprocess,
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/yass/merge/__init__.py", line 5, in <module>
	    from yass.merge.run import run
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/yass/merge/run.py", line 9, in <module>
	    from yass.merge.merge import TemplateMerge
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/yass/merge/merge.py", line 8, in <module>
	    from diptest import diptest as dp
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/diptest/__init__.py", line 6, in <module>
	    from diptest._interface import dip, diptest
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/diptest/_interface.py", line 2, in <module>
	    from diptest import _diptest
	  File "__init__.pxd", line 178, in init diptest._diptest (src/diptest/_diptest.c:16630)
	ValueError: numpy.ndarray has the wrong size, try recompiling


Ubuntu 20.04 - Cuda toolkit 10.0 - Python3.7 - Pytorch 1.2 - gcc4.8
This one gives a different error:

```
	Traceback (most recent call last):
	  File "/home/olivier/anaconda3/envs/yass/bin/yass", line 33, in <module>
	    sys.exit(load_entry_point('yass-algorithm', 'console_scripts', 'yass')())
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
	    return get_distribution(dist).load_entry_point(group, name)
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
	    return ep.load()
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
	    return self.resolve()
	  File "/home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
	    module = __import__(self.module_name, fromlist=['__name__'], level=0)
	  File "/home/olivier/Documents/PYTHON/yass/src/yass/command_line.py", line 28, in <module>
	    from yass import pipeline
	  File "/home/olivier/Documents/PYTHON/yass/src/yass/pipeline.py", line 31, in <module>
	    from yass import (preprocess, detect, cluster, postprocess,
	  File "/home/olivier/Documents/PYTHON/yass/src/yass/deconvolve/__init__.py", line 1, in <module>
	    from yass.deconvolve.run import run
	  File "/home/olivier/Documents/PYTHON/yass/src/yass/deconvolve/run.py", line 14, in <module>
	    from yass.deconvolve.match_pursuit_gpu_new import deconvGPU
	  File "/home/olivier/Documents/PYTHON/yass/src/yass/deconvolve/match_pursuit_gpu_new.py", line 16, in <module>
	    import cudaSpline as deconv
	ImportError: /home/olivier/anaconda3/envs/yass/lib/python3.7/site-packages/deconv-0.0.0-py3.7-linux-x86_64.egg/cudaSpline.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
```

And those two don't even compile
Ubuntu 20.04 - Cuda toolkit 10.0 - Python3.7 - Pytorch 1.2 - gcc9
Ubuntu 20.04 - Cuda toolkit 10.0 - Python3.7 - Pytorch 1.2 - gcc6


It seems it's impossible to get it on my system, so I guess we'll have to go the Docker way. Did you have any luck on your side ?

**Comment by samuelgarcia** [comment]
Salut Olivier.
Same for me. Long fight to try installing but no succes.
The only think I have not try is to install conda.
But this installation will break too much stuff on my machine.
The second error you have is one I had and but also had other ones.
Bonne journée.

**Comment by catubc** [comment]
Hello. We have not tested yass with Ubuntu 20.04, not clear if there are some issues with it, but we don't have an Ubuntu 20.04 system available.
If you have an SSH setup, please let email me and I can test and install yass for you. You can also email me directly for any other questions:

mitelutco@gmail.com

catubc

**Comment by somalcy** [comment]
Hi, I got same error. @oliche 
Ubuntu 20.04 - Cuda toolkit 10.0 - Python3.7 - Pytorch 1.2 - gcc4.8 - g++4.9 - NVIDIA 460.73.01

> Traceback (most recent call last):
  File "/home/user/anaconda3/envs/yass/bin/yass", line 5, in <module>
    from yass.command_line import cli
  File "/home/user/anaconda3/envs/yass/lib/python3.7/site-packages/yass/command_line.py", line 28, in <module>
    from yass import pipeline
  File "/home/user/anaconda3/envs/yass/lib/python3.7/site-packages/yass/pipeline.py", line 31, in <module>
    from yass import (preprocess, detect, cluster, postprocess,
  File "/home/user/anaconda3/envs/yass/lib/python3.7/site-packages/yass/deconvolve/__init__.py", line 1, in <module>
    from yass.deconvolve.run import run
  File "/home/user/anaconda3/envs/yass/lib/python3.7/site-packages/yass/deconvolve/run.py", line 14, in <module>
    from yass.deconvolve.match_pursuit_gpu_new import deconvGPU
  File "/home/user/anaconda3/envs/yass/lib/python3.7/site-packages/yass/deconvolve/match_pursuit_gpu_new.py", line 16, in <module>
    import cudaSpline as deconv
ImportError: /home/user/anaconda3/envs/yass/lib/python3.7/site-packages/deconv-0.0.0-py3.7-linux-x86_64.egg/cudaSpline.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

Can `Ubuntu 20.04` or `NVIDIA driver` lead this error? 
The CUDA code compiling seemed to be successed.

LCY

**Comment by mishek-thapa** [comment]
@catubc I also have this error. Could I also get some help with my installation?

**Comment by catubc** [comment]
Hello.
Yes, for now Yass does not run on Ubuntu 20.04, but we are working on it. There is a solution that should be available in the next month or so from spike-interface:

https://github.com/SpikeInterface
