### ISSUE TITLE
Problem while running the train function 

### ISSUE THREAD

**Issue by botwithabeard** [paninski-lab/yass#344]
I'm running yass on Google Colab, and on my own data (one channel data), however when I run the
> !yass train config.yaml 

this command it gives me the following error

```bash
  DISPLAY IS NOT SETUP, Use command line only
yass.pipeline_nn_training@run 23/08/2021 08:56:19 INFO YASS version: 2.0
yass.preprocess.run@run 23/08/2021 08:56:19 INFO # of chunks: 263
yass.preprocess.run@run 23/08/2021 08:56:19 INFO Creating temporary folder: tmp/preprocess
yass.preprocess.run@run 23/08/2021 08:56:19 INFO Output dtype for transformed data will be float32
264it [00:36,  7.28it/s]
yass.preprocess.util@merge_filtered_files 23/08/2021 08:56:57 INFO ...saving standardized file: tmp/preprocess/standardized.bin
yass.preprocess.run@run 23/08/2021 08:57:00 INFO Saving params...
yass.pipeline_nn_training@run 23/08/2021 08:57:00 INFO DETECTION
   batch length to (sec):  10  (longer increase speed a bit)
   length of each seg (sec):  0.5
64it [00:04, 14.52it/s]
yass.detect.output@gather_result 23/08/2021 08:57:04 INFO gather detected spikes
yass.detect.output@gather_result 23/08/2021 08:57:05 INFO Total 0 spikes detected
yass.detect.output@gather_result 23/08/2021 08:57:05 INFO Total 0 spikes survived after deduplication
yass.pipeline_nn_training@run 23/08/2021 08:57:05 INFO CLUSTERING
yass.cluster.run@run 23/08/2021 08:57:05 INFO Split on PTP
yass.cluster.ptp_split@run_split_on_ptp 23/08/2021 08:57:05 INFO Get Spike PTP
  0% 0/60 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/yass", line 33, in <module>
    sys.exit(load_entry_point('yass-algorithm', 'console_scripts', 'yass')())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/content/yass/src/yass/command_line.py", line 129, in train
    output_dir=output_dir)#,
  File "/content/yass/src/yass/pipeline_nn_training.py", line 170, in run
    full_run=True)
  File "/content/yass/src/yass/cluster/run.py", line 156, in run
    denoiser)
  File "/content/yass/src/yass/cluster/ptp_split.py", line 50, in run_split_on_ptp
    ptp_raw, ptp_deno = getptp.compute_ptps()
  File "/content/yass/src/yass/cluster/getptp.py", line 87, in compute_ptps
    del dat, idx_in, spike_index_batch, t_index, c_index, wfs, ptps_raw
UnboundLocalError: local variable 't_index' referenced before assignment```

Any advice on how to rectify this? Thank you.

**Comment by catubc** [comment]
Hello
We've never seen this error before. It might occur if you recordings are too short or there are no spikes to loop over. Yass works best on longer datasets with sufficient spikes.

**Comment by botwithabeard** [comment]
Okay thanks!
