### ISSUE TITLE
Yass example fails

### ISSUE THREAD

**Issue by calvinytong** [paninski-lab/yass#83]
Running `yass sort config_sample.yaml` yields the following traceback. I suspect this is because of the latest 2+3 merge 

fyi @edublancas @jinhyunglee 

```
Traceback (most recent call last):
  File "/Users/calvin/anaconda3/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm', 'console_scripts', 'yass')()
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/command_line.py", line 59, in sort
    output_dir=output_dir, complete=complete)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/command_line.py", line 102, in _run_pipeline
    output_directory=output_dir)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/process/run.py", line 88, in run
    if CONFIG.clustering.clustering_method == '2+3':
  File "/Users/calvin/Documents/Columbia/yass/src/yass/config/config.py", line 62, in __getattr__
    return FrozenJSON(self._data[name])
KeyError: 'clustering_method'
```

**Comment by nd2506** [comment]
Use the config_sample_complete file to run the example. That is the updated config file.

**Comment by calvinytong** [comment]
Okay can we remove the other config then and rename complete to just config_sample? It is a little confusing to have both if one doesn't work.

**Comment by nd2506** [comment]
You can remove it. I believe it's for running parts of the pipeline which do not require all the keys.

**Comment by calvinytong** [comment]
I'm currently getting this traceback when running the complete example 

```
Traceback (most recent call last):
  File "/Users/calvin/anaconda3/bin/yass", line 11, in <module>
    load_entry_point('yass-algorithm', 'console_scripts', 'yass')()
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/command_line.py", line 59, in sort
    output_dir=output_dir, complete=complete)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/command_line.py", line 102, in _run_pipeline
    output_directory=output_dir)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/process/run.py", line 388, in run
    CONFIG.templatesMaxShift, merge_threshold, CONFIG.neighChannels)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/process/templates.py", line 27, in get_and_merge_templates
    spike_size + template_max_shift)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/process/templates.py", line 18, in get_templates
    spe = SpikeTrainExplorer(spike_train_clear, re)
  File "/Users/calvin/Documents/Columbia/yass/src/yass/explore/explorers.py", line 107, in __init__
    self.templates, self.weights = self._compute_templates()
  File "/Users/calvin/Documents/Columbia/yass/src/yass/explore/explorers.py", line 155, in _compute_templates
    templates = np.stack(templates, axis=2)
  File "/Users/calvin/anaconda3/lib/python3.6/site-packages/numpy/core/shape_base.py", line 350, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
````

**Comment by jinhyunglee** [comment]
don't remove config_sample. it is what users should use.
It contains the least amount of configuration that users need. (others are set to default as in assets/config/validator.py

config_sample_complete is for us or other researchers who want to try different parameter values.

@nd2506 make sure that 2+3 model works with config_sample too.

**Comment by edublancas** [comment]
`config_sample_complete` has documentation for every parameter in the settings, some have default values, that's why we have `config_sample`, just as @jinhyunglee said.

@calvinytong you are getting an error because the data is so small that it does not generate any templates

I think we can fix this by using a larger dataset in the tests but I don't want to include big files in the repo, I think the integration tests will fix this issues

**Comment by nd2506** [comment]
That should have been a different error. I think it was valueerror or local unbound parameter error

**Comment by nd2506** [comment]
Added the required keys in config_sample. Pushed changes to my branch. Let me just finish with adding 2+3 for threshold detection and then we can merge to master
